name: GCP CI-CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: devops-handson-482913
      REGION: europe-west1
      IMAGE: europe-west1-docker.pkg.dev/devops-handson-482913/devops-repo/app

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Apply (Infra only)
      working-directory: terraform
      run: |
        terraform apply -auto-approve \
          -var="project_id=$PROJECT_ID" \
          -var="region=$REGION" \
          -var="image=gcr.io/cloudrun/hello"

    - name: Configure Docker
      run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

    - name: Build & Push Image
      run: |
        docker build -t $IMAGE:$GITHUB_SHA .
        docker push $IMAGE:$GITHUB_SHA

    - name: Terraform Apply (Deploy app)
      working-directory: terraform
      run: |
        terraform apply -auto-approve \
          -var="project_id=$PROJECT_ID" \
          -var="region=$REGION" \
          -var="image=$IMAGE:$GITHUB_SHA"
